#!/bin/bash

# test shlvl

echo "echo \"🦥■■■  Im here ■■■🦥\""| bash >> bash.txt 


echo "echo $SHLVL, export SHLVL=0" | bash > bash.txt//230826動作確認
echo "echo $SHLVL, export SHLVL=998" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=999" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=1000" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=+42" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=-1" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=4294967295" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=4294967296" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=-4294967296" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=-4294967297" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=a" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf "\t\n\v\f\r 42"`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42 "`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42\t"`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42\v"`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42\n"`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42\f"`" | bash >> bash.txt
echo "echo $SHLVL, export SHLVL=`printf " 42\r"`" | bash >> bash.txt

